### ISSUE TITLE
Can not get initial state on first load

### ISSUE THREAD

**Issue by Gujionsen** [olegpisklov/vue-ssr-simple-setup#2]
Hello Oleg
Thanks for this good starting point!

It does not show user list on first load in dev mode. It seems store can not get initial state. After page refresh everything is ok. 
I just cloned and run the code without any modifications.

Could you advice something? how can I solve this.

Thanks in advance!

![initial_state_problem](https://user-images.githubusercontent.com/11720178/70037919-d5a59180-15d0-11ea-89f4-985804358983.jpg)

**Comment by olegpisklov** [comment]
Hello, thank you for reporting this issue, I was able to reproduce it. Seems like the
__INITIAL_SATE__ variable is undefined in this case. I'll fix it and let
you know then.

**Comment by olegpisklov** [comment]
[Fixed](https://github.com/olegpisklov/vue-ssr-simple-setup/commit/4d8dfa6893801ff0fe81cf557392630905348696)
