### ISSUE TITLE
It seems like not working on production.

### ISSUE THREAD

**Issue by yuhua-chen** [olegpisklov/vue-ssr-simple-setup#3]
I run the code in production and it will generate the js and css with hash. However, the `index.html` loads the script and style without hash like this:
```
// The built script is: app.a0329b9f830ad7fe00f3.js
<script src="public/app.js"></script>
```

Did I do something wrong with it? Thank you.

**Comment by olegpisklov** [comment]
Serving static assets is out of the scope of this setup. The goal was to keep it as simple as possible and to get you to the point when you have an app build ready to be used in production.  The way of how to deliver it is up to a developer. Sorry if it was not clear.

**Comment by yuhua-chen** [comment]
Thanks for the reply. There's no problem and I am going to close this issue. :)
