### ISSUE TITLE
Where is memory-fs coming from in config/setup-dev-server.js line 10

### ISSUE THREAD

**Issue by aysiscore** [olegpisklov/vue-ssr-simple-setup#4]
In config/setup-dev-server.js the MFS requires memory-fs, but that is not in the package.json file anywhere.

If related, then npm memory-fs says it is deprecated and should now use https://www.npmjs.com/package/memfs

**Comment by olegpisklov** [comment]
Thank you for reporting it, **memory-fs** module comes with **webpack**, it probably should be installed explicitly. 

For now, it can't be simply replaced with **memfs** due to this issue https://github.com/streamich/memfs/issues/404.
