### ISSUE TITLE
Development using nodemon src/server.js does not run Webpack client build to allow ES6+ syntax

### ISSUE THREAD

**Issue by aysiscore** [olegpisklov/vue-ssr-simple-setup#7]
To start dev mode the app uses nodemon like nodemon src/server.js

If we want to use ES6+ syntax in src/server.js then `webpack.base.config.js`  uses `babel-loader`. 

However `babel-loader` does not seem to work in development. If I use ES6 `import` statements in `server.js` and run `npm run dev` then I get errors like:

> import express from 'express';
> ^^^^^^
> SyntaxError: Cannot use import statement outside a module

But if I run `npm build:client` and `npm build:server` there are no errors. This is because Webpack does not get a chance to build `server.js` before it runs `nodemon src/server.js`. I don't know how to solve it.

**Comment by olegpisklov** [comment]
`./server.js` file is not transpiled by webpack in this setup, I don't think it's really necessary. Webpack is used here only for transpiling/bundling the client code. Also please see the info regarding using ECMAScript modules in node.js here https://nodejs.org/api/esm.html

**Comment by aysiscore** [comment]
Then that means server.js and setup-dev-server.js cannot be written in ES6+ code. I solved it by installing `babel-node` and then changing the package.json script to `"dev": "cross-env NODE_ENV=development nodemon --exec babel-node src/server.js"`. Now all files can use ES6+!

**Comment by olegpisklov** [comment]
You can use ES6+ syntax in node.js without transpiling, as you can see `./server.js` is written with `async/await` and other cool stuff.  Basically you're transpiling node.js files only for ES modules support.
